let data = [
    {
        type:"email",
        body: "Hey John, just wanted to follow up on our conversation yesterday. Do you think the software is a good fit for your team? I'm happy to set up another demo or go over pricing options",
        conversationId: '123',
        _id:"email1",
        owner: "alan@salescapture.ai",
        timeStamp: "Yesterday 10:14 AM",
        subject: "hi",
        ownerMessage:true,
    },
   //John emails
    {
        type:"email",
        body: "Hey John, just wanted to follow up on our conversation yesterday. Do you think the software is a good fit for your team? I'm happy to set up another demo or go over pricing options",
        conversationId: '123',
        _id:"email1",
        owner: "alan@salescapture.ai",
        timeStamp: "Yesterday 10:14 AM",
        subject: "hi",
        ownerMessage:true,
    },
    {
        type:"email",
        body: "No I can't this week.",
        conversationId: '123',
        _id:"email2",
        owner: "alan@salescapture.ai",
        subject: "hi",
        timeStamp: "Today 9:14 AM",
        ownerMessage:false,
    },
    //Jane emails
    {
        type:"email",
        body: "Hi Jane, AI can find the contacts you need to reach out to TODAY. Let me know if you can connect today.",
        conversationId: '1234',
        _id:"email3",
        owner: "alan@salescapture.ai",
        timeStamp: "Yesterday 10:14 AM",
        subject: "hi",
        ownerMessage:true,
    },
    {
        type:"email",
        body: "Sure I have time arround 3pm tomorrow afternoon",
        conversationId: '1234',
        _id:"email4",
        owner: "alan@salescapture.ai",
        subject: "hi",
        timeStamp: "Today 9:14 AM",
        ownerMessage:false,
    },
    //Taylor emails
    {
        type:"email",

        body: "Hey Taylor Just let me know if it would be good to meet today or not.",
        conversationId: '1235',
        // suggestion:true,
        _id:"email5",
        owner:"taylor@flinnapps.com",
        timeStamp: "Yesterday 10:14 AM",
        subject: "hi",
        ownerMessage:true,
    },
    {
        type:"email",
        body: "No I can't this week.",
        conversationId: '1235',
        _id:"email6",
        owner: "alan@salescapture.ai",
        subject: "hi",
        timeStamp: "Today 9:14 AM",
        ownerMessage:false,
    },

    {
        type:"conversation",
        _id:"123",
        contact: "taylormdavidson@gmail.com",
        contactName: "John Doe",
        timeStamp: "Today 2:15 pm",
        recentMessage:"Hey, how's it going?",
        owner:"alan@salescapture.com"
    },
    {
        type:"conversation",
        _id:"1234",
        suggestion:true,
        contact: "taylormdavidson@gmail.com",
        contactName: "Jane Doe",
        timeStamp: "Today 2:15 pm",
        recentMessage:"Hey, how's it going?",
        owner:"alan@salescapture.com"
    },
    {
        "type": "contact",
        "_id": "contact1",
        "firstName": "Mubarak",
        "email": "mubarak@vividinfotech.com",
        "owner": "alan@salescapture.com",
        "lastName": "Basha",
        "linkedIn": "https://www.linkedin.com/in/mubarak-basha-6a705516",
        "company": "VIVID Infotech Software Solutions (P) Ltd",
        "title": "Founder & CEO www.vividinfotech.com",
        "connectedOn": "19 May 2021",
        "mobile": "NA",
        "tags": "linkedin"
    },
    {
        "type": "contact",
        "_id": "contact2",
        "firstName": "Nate",
        "email": "nmaguire@strativise.com",
        "owner": "alan@salescapture.com",
        "lastName": "Maguire",
        "linkedIn": "https://www.linkedin.com/in/natemaguire",
        "company": "Strativise, Inc.",
        "title": "Founder & CEO",
        "connectedOn": "22 Apr 2021",
        "mobile": "949-390-4532",
        "tags": "linkedin"
    },
    
  
  
    {
        type:"research",
        _id: "research1",
        name:"Vp of Sales",
        email:"taylormdavidson@gmail.com",
        owner:"alan@salescapture.com ",
        AIPrompt:"Search for all the Vp of Sales in Utah",
        searchFrequency:"Daily"
        },
  
    {
        "type": "potentialProspect",
        "_id": "prospect1",
        "firstName": "Mubarak",
        "email": "mubarak@vividinfotech.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Basha",
        "linkedIn": "https://www.linkedin.com/in/mubarak-basha-6a705516",
        "company": "VIVID Infotech Software Solutions (P) Ltd",
        "title": "Founder & CEO www.vividinfotech.com",
        "connectedOn": "19 May 2021",
        "mobile": "NA",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect2",
        "firstName": "Nate",
        "email": "nmaguire@strativise.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Maguire",
        "linkedIn": "https://www.linkedin.com/in/natemaguire",
        "company": "Strativise, Inc.",
        "title": "Founder & CEO",
        "connectedOn": "22 Apr 2021",
        "mobile": "949-390-4532",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect3",
        "firstName": "Dave",
        "email": "dave@turtlebayventures.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "McKenna",
        "linkedIn": "https://www.linkedin.com/in/davemckenna2",
        "company": "Monarch Real Estate Partners",
        "title": "Managing Partner",
        "connectedOn": "16 Aug 2019",
        "mobile": "214-783-0156",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect4",
        "firstName": "R.W.",
        "email": "rw@hollemanfarms.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Holleman",
        "linkedIn": "https://www.linkedin.com/in/rwholleman",
        "company": "Rain",
        "title": "Head of Enterprise Sales",
        "connectedOn": "14 May 2019",
        "mobile": "972-814-6304",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect5",
        "firstName": "Brian",
        "email": "Brian.Reed@DigitalAutoStrategy.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Reed",
        "linkedIn": "https://www.linkedin.com/in/digitalautoadvisors",
        "company": "Car Capital Technologies, Inc.",
        "title": "Car Capital - Chairman of the Board",
        "connectedOn": "24 Apr 2019",
        "mobile": "817.851.8229",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect6",
        "firstName": "Thomas",
        "email": "tom.wilson@graphiumhealth.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Wilson",
        "linkedIn": "https://www.linkedin.com/in/thomas-t-wilson-70846b15",
        "company": "Crest Expansion Group",
        "title": "Co-Owner",
        "connectedOn": "18 Apr 2019",
        "mobile": "2147895978",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect7",
        "firstName": "Shawn",
        "email": "shawnlima@msn.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Lima",
        "linkedIn": "https://www.linkedin.com/in/shawnlima",
        "company": "Advisor labs",
        "title": "Enterprise Account Executive",
        "connectedOn": "12 Apr 2019",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect8",
        "firstName": "Damon",
        "email": "damon@exityourway.us",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Pistulka √",
        "linkedIn": "https://www.linkedin.com/in/damonpistulka",
        "company": "B2Btail",
        "title": "Relentless Business Growth Advocate",
        "connectedOn": "27 Sep 2018",
        "mobile": "425-654-7757",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect9",
        "firstName": "Vishal",
        "email": "vishalrjoshi@live.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Joshi",
        "linkedIn": "https://www.linkedin.com/in/vishaljoshivishalrjoshi@live.com",
        "company": "JoyCo",
        "title": "Founder & CEO",
        "connectedOn": "18 Sep 2018",
        "mobile": "4252332749",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect10",
        "firstName": "John",
        "email": "jc.murray@jcmurrayii.dev",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Murray",
        "linkedIn": "https://www.linkedin.com/in/jcmurray2",
        "company": "VGS",
        "title": "Principal Software Engineer, Payments",
        "connectedOn": "29 Aug 2018",
        "mobile": "719 345 7617",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect11",
        "firstName": "David",
        "email": "david.sanders@revellence.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Sanders",
        "linkedIn": "https://www.linkedin.com/in/dwsandrs",
        "company": "Valenta",
        "title": "Chief Revenue Officer (CRO)",
        "connectedOn": "29 Aug 2018",
        "mobile": "678-429-6245",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect12",
        "firstName": "Sherry",
        "email": "sherry@mac.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Warburton",
        "linkedIn": "https://www.linkedin.com/in/sherry-warburtonus",
        "company": "Comcast",
        "title": "Sr Director - New Device Lifecycle, Special Projects, Initiatives and Ai Projects",
        "connectedOn": "29 Aug 2018",
        "tags": "linkedin"
    },
    {
        "type": "potentialProspect",
        "_id": "prospect13",
        "firstName": "John",
        "email": "jbeane@memcpu.com",
        "owner": "alan@salescapture.com",
        "researchId": "research1",
        "lastName": "Beane",
        "linkedIn": "https://www.linkedin.com/in/jbeane",
        "company": "MemComputing, Inc.",
        "title": "Founder & Chief Executive Officer",
        "connectedOn": "06 Jul 2018",
        "tags": "linkedin"
    },
<<<<<<< HEAD
    {
        type:"research",
        _id: "research1",
        name:"research1",
        owner:"alan@salescapture.com "
        },
    {
        type:"client",
        _id:"client1",
        name:"firstClient"
       
    },
    {
        type:"client",
        _id:"client2",
        name:"jared"
    },
    {
        type:"AIPrompt",
        _id:"ai1",

    }
=======
    
>>>>>>> 245776a38f3327b259571a8dbd4e68be017b4592
]

export {data}